apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: local-registry/app-b:latest
        imagePullPolicy: Never # this is required for running locally in docker desktop
        ports:
        - containerPort: 5001